server:
  dataStorage:
    enabled: true
  standalone:
    enabled: false
  injector:
    enabled: true
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "raft" {
          path = "/vault/data"
          retry_join {
            auto_join_scheme = "http"
            auto_join = "provider=k8s label_selector=\"app.kubernetes.io/name={{ include "vault.name" . }},app.kubernetes.io/instance={{ .Release.Name }},component=server\",namespace={{ .Release.Namespace }}"
            # leader_tls_servername = "vault"
            # leader_ca_cert_file = "/vault/userconfig/vault-server-tls/vault.ca"
            # leader_client_key_file = "/vault/userconfig/vault-server-tls/vault.key"
            # leader_client_cert_file = "/vault/userconfig/vault-server-tls/vault.crt"
            # auto_join_scheme = "https"
          }
        }
        service_registration "kubernetes" {}

ui:
  enabled: true

